language: cpp
group: travis_latest
dist: xenial

matrix:
  include:
  - os: linux

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

script:
  - qmake "LIBS+= -lstdc++fs"
  - make
  - ./organsize
# - qmake "CONFIG+=test" organsize.pro # Compile for testing
# - make
# ./organsize
