######################################################################
# Automatically generated by qmake (3.0) Sun Sep 2 16:26:13 2018
######################################################################

TEMPLATE = app
TARGET = organsize
QT += core widgets
CONFIG += c++11
INCLUDEPATH += .

# Input
HEADERS += analysis.h dirFile.h gui.h organsize.h
SOURCES += analysis.cpp dirFile.cpp gui.cpp main.cpp organsize.cpp
